services:
  joulescope-logger:
    build: ./backend
    container_name: joulescope-logger
    privileged: true
    ports:
      - "8081:8080"
    volumes:
      # SD externo (Radxa). Para dev local: ./logs:/app/logs
      - /mnt/external_sd/logs:/app/logs
      - /dev:/dev
      - /run/udev:/run/udev:ro
    environment:
      - TZ=America/Sao_Paulo
      - LOG_DIR=/app/logs
      - PORT=8080
    restart: always
